# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BPT_Overlay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BPT_Overlay
  pod 'RoundedViews', '~> 1.0'

  target 'BPT_OverlayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BPT_OverlayUITests' do
    # Pods for testing
  end

end
